import { chromium } from 'playwright'; import path from 'path'; import fs from 'fs';
const fd = path.resolve('node_modules/@fontsource');
const css = [400,500,600,700,800].map(w=>`@font-face{font-family:'Inter';font-weight:${w};src:url('file://${fd}/inter/files/inter-latin-${w}-normal.woff2') format('woff2');}`).join('')+[400,500,600,700].map(w=>`@font-face{font-family:'Space Grotesk';font-weight:${w};src:url('file://${fd}/space-grotesk/files/space-grotesk-latin-${w}-normal.woff2') format('woff2');}`).join('');
const [,,file,dir,pct='']=process.argv;
const b=await chromium.launch(); const p=await (await b.newContext({viewport:{width:1500,height:1000}})).newPage();
await p.route('**/*', r=>{const u=r.request().url(); if(u.startsWith('file://')) return r.continue(); if(u.includes('fonts.googleapis.com')) return r.fulfill({contentType:'text/css',body:css}); return r.abort();});
await p.goto('file://'+path.resolve(file)); await p.evaluate(()=>document.fonts.ready);
if(pct) await p.evaluate(v=>document.documentElement.style.fontSize=v+'%',pct);
if(process.env.HIDE) await p.addStyleTag({content:".sim-toggle,.masthead,section.handover,.spec,.section-title,.item-caption{display:none !important}"}); await p.waitForTimeout(300); fs.mkdirSync(dir,{recursive:true});
const ph=await p.$$('.phone'); for(let i=0;i<ph.length;i++) await ph[i].screenshot({path:`${dir}/p${i+1}.png`});
await b.close();
